### ISSUE TITLE
Labels from 5.8.1 not compatible with toolkit

### ISSUE THREAD

**Issue by G-nn-r** [wkentaro/labelme#1569]
### Provide environment information

Default conda installation of  5.8.1 with miniconda

### What OS are you using?

Windows 11

### Describe the Bug

The current labelme version has two issues when creating label files:
1. The mask may be saved in uint8 format. `labelmetk json-to-mask` fails therefore with the error `error: expected mask.dtype=bool, but got uint8`. 
    - As a hotfix, this can be solved by modifying the file from the toolkit (`json_to_mask.py`, on Windows located e.g. at `C:\envs\my_labelme_env\Lib\site-packages\labelme_toolkit\_cli\_json_to_mask.py`). In [line 35](https://github.com/labelmeai/toolkit/blob/5fb98a976d7b975e426bddcce962c024803bf69d/labelme_toolkit/_cli/_json_to_mask.py#L35) (`shape_mask = _json.image_b64data_to_ndarray(b64data=shape["mask"])`) needs to be appended `.astype(np.bool)`. So the whole line should read `shape_mask = _json.image_b64data_to_ndarray(b64data=shape["mask"]).astype(np.bool)`
2. The `points` are saved as floats instead of integers. This causes an error much later for `labelmetk json-to-mask` fails when trying to call `image.paste(mask, (xmin, ymin))` in `_labelme.py`: `error: 'numpy.float64' object cannot be interpreted as an integer`. Again, this can be hotfixed, this time by inserting an additional line to `json_to_mask.py`. In line 38, you need to add: `shape["points"] = [[int(e) for e in sublist] for sublist in shape["points"]]`

### Expected Behavior

`labelmetk json-to-mask`  should run through without the currently necessary hotfixes.

**Comment by wkentaro** [comment]
Thank you for the report.

I got a similar report in Discord, and am working on it. I’ll get back to you once done.

![image](https://github.com/user-attachments/assets/09ecc53e-8a28-401c-a5e5-33995dc02554)

**Comment by wkentaro** [comment]
@G-nn-r I've released labelme-toolkit 0.1.2, which supports shape_type="mask" in json-to-mask, json-to-masks, and export-to-voc. https://labelme.io/docs/install-toolkit

Let me know if it works for you.

<img src=https://github.com/user-attachments/assets/3da515ca-5fe4-4d2b-af4b-340f3357620b width=300> <img src=https://github.com/user-attachments/assets/728a1089-0526-4949-ab46-83c6126a5aad width=400>

**Comment by amughrabi** [comment]
I used v1.3.3, and I still have the same problem that mentioned in this thread.
