### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by mfaramarzi** [wkentaro/labelme#677]
@latticetower @wkentaro 

when running `labelme` the following error pops up

![image](https://user-images.githubusercontent.com/44882423/84151461-69995f80-aa31-11ea-89d0-25edcde7ee3f.png)
following [this stack](https://stackoverflow.com/questions/60042568/this-application-failed-to-start-because-no-qt-platform-plugin-could-be-initiali) I installed open-cv by `pip3 install opencv-python==4.1.2.30  ` but it didnt fix the problem either.

**Comment by wkentaro** [comment]
labelme does not depend on opencv.

**Comment by mfaramarzi** [comment]
> labelme does not depend on opencv.

What would you think the problem could be?

**Comment by wkentaro** [comment]
I’m not sure, but you could try creating a clean anaconda env and install labelme. (since labelme is working on CI)

**Comment by mfaramarzi** [comment]
>  labelme is working on CI

I try. By the what does it mean here by CI? computer interface?

**Comment by wkentaro** [comment]
CI is the abbreviation of continuous integration. For every PRs or pushes to master, it tests installation and examples on test servers.
https://github.com/wkentaro/labelme/blob/master/.github/workflows/ci.yml

You can see all jobs of the latest CI run here:
https://github.com/wkentaro/labelme/runs/723111589?check_suite_focus=true
It tests on different Python versions (python2/3), OS (mac/linux/windows),  and etc.

**Comment by njustczr** [comment]
> I’m not sure, but you could try creating a clean anaconda env and install labelme. (since labelme is working on CI)

i have the same problem, and create a new conda env can not fix the problem

**Comment by mfaramarzi** [comment]
> 
> 
> > I’m not sure, but you could try creating a clean anaconda env and install labelme. (since labelme is working on CI)
> 
> i have the same problem, and create a new conda env can not fix the problem

I fixed it by "creating a clean anaconda env and install labelme."

**Comment by wkentaro** [comment]
This is how I do to create a clean anaconda env

```
cd /tmp
git clone https://github.com/wkentaro/labelme.git
cd labelme

wget https://raw.githubusercontent.com/wkentaro/dotfiles/master/local/bin/install_anaconda3.sh
bash ./install_anaconda3.sh .
source .anaconda3/bin/activate

pip install -e .

cd examples/semantic_segmentation
labelme data_annotated/ --labels labels.txt --nodata
```

**Comment by a-asterisk** [comment]
I created a clean anaconda env like you described before but still get the same error:
![Screenshot from 2020-07-14 10-20-08](https://user-images.githubusercontent.com/57945101/87402297-a40b9480-c5bb-11ea-8c61-661d5be58596.png)

**Comment by Frank1126lin** [comment]
Same issue when I open labelme.
```
Cannot load library /home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

**Comment by way790110** [comment]
I solved it by install libxcb-xinerama0

sudo apt install libxcb-xinerama0

**Comment by ogencoglu** [comment]
> I solved it by install libxcb-xinerama0
> 
> sudo apt install libxcb-xinerama0

This also solved my issue.

**Comment by ogencoglu** [comment]
> Same issue when I open labelme.
> 
> ```
> Cannot load library /home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
> QLibraryPrivate::loadPlugin failed on "/home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/frank/miniconda3/envs/label/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted (core dumped)
> ```

Same here. Installing `libxcb-xinerama0` did not fix it either.

**Comment by laoyandujiang** [comment]
> I solved it by install libxcb-xinerama0
> 
> sudo apt install libxcb-xinerama0

Thanks a lot. This also solved my issue.

**Comment by zhuyuanxiang** [comment]
I use 'pip install labelme' and fix this problem.

PS: Plz use 'conda uninstall labelme' to remove the conda installed labelme.

**Comment by zhuyuanxiang** [comment]
[labelme-jgt.yml](https://github.com/user-attachments/files/18274528/labelme-jgt.md)
This file that was used by conda can fix the problem.
