### ISSUE TITLE
cli/json_to_dataset.py made an error in dealing with rotating semantic split pictures.[BUG]

### ISSUE THREAD

**Issue by 1753939775** [wkentaro/labelme#773]
**Describe the bug**
cli/json_to_dataset.py can't handle rotating pictures.

Pictures taken with mobile phones has a rotation information in exfi.

I use labelme labeled rotating pictures token by phone.
Then, i use cli/json_to_dataset.py to change my labeled data for semantic segmentation.
I found it open images as follow:
    with open(imagePath, 'rb') as f:
            imageData = f.read()
            imageData = base64.b64encode(imageData).decode('utf-8')
    img = utils.img_b64_to_arr(imageData)
it seems that it will not handle rotation issues.

when we labeling through labelme to labeled our pictures,it use PIL.images to open pictures.
It will deal with rotation.

SO, if we use json_to_dataset.py to processing  rotating pictures,it will be wrong.

**Expected behavior**

**Screenshots**
maybe we cang modify the json_to_dataset.py to solving it

**Desktop (please complete the following information):**
 - OS: windows10
 - Labelme Version  4.2.10

**Comment by wkentaro** [comment]
I think this should be fixed via https://github.com/wkentaro/labelme/blob/1a425b25fd544af309062099fb3f0f92327df520/labelme/label_file.py#L56
Please comment if not.

**Comment by leozjr** [comment]
> I think this should be fixed via
> 
> https://github.com/wkentaro/labelme/blob/1a425b25fd544af309062099fb3f0f92327df520/labelme/label_file.py#L56
> 
> 
> Please comment if not.

I’m still encountering this error. I noticed that the change above has corrected the annotation part, but for the json_to_dataset or export_json scripts, their input images still haven’t correctly applied the exif information. 

So I think this line ‘img_pil = utils.apply_exif_orientation(img_pil)’ should also be added in the `labelme\utils\image.py`：
```
from labelme import utils

def img_data_to_pil(img_data):
    f = io.BytesIO()
    f.write(img_data)
    img_pil = PIL.Image.open(f)
    img_pil = utils.apply_exif_orientation(img_pil)
    return img_pil
```
